<a href="https://colab.research.google.com/github/Sofvauc/ENTREGAS/blob/main/Copia_de_Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
# @title Texto de título predeterminado
import numpy as np

# Crear un arreglo de ceros de tamaño 12
arreglo_ceros = np.zeros(12)

print("Arreglo de ceros:")
print(arreglo_ceros)

Arreglo de ceros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arreglo_ceros = np.zeros(10)
arreglo_ceros[4] = 10

print("Arreglo:")
print(arreglo_ceros)


Arreglo:
[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
arreglo = np.arange(10,50)

print("arreglo:")
print(arreglo)

arreglo:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
arreglo = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(arreglo)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
arreglo = np.random.randn(100)
print("arreglo:")
print(arreglo)

print("media de mi arreglo")
np.mean(arreglo)

arreglo:
[ 1.04064828  1.33199424 -0.8214637   2.38924566  0.74284248 -0.45639067
  0.22841352  1.91493196 -0.55510983 -0.75325708  0.1420783   1.62822372
 -0.76953979  2.89834319 -0.21882343 -1.15891495 -1.60503605  0.2613277
  0.17757839 -0.46859742  0.27475732  0.58716176 -0.17942426 -0.6558532
  0.18269334  0.88961893  1.37613586  0.47151274  0.71875156  0.22045788
 -0.33100308 -0.85726833  0.10122426  0.36618125 -0.5134687   0.09657439
  1.43390614  0.24650602 -0.55874654 -0.68134274 -0.43915425 -0.70520587
 -0.1064867  -1.02143541  0.51825484  0.26346044 -0.63257042 -0.18215895
  0.12101606 -1.01949268  0.96121969  0.41581469  0.25956566  0.14775528
  0.91565847 -0.41927621  0.15151904  0.53008087  1.40279532  0.82476266
 -0.60864227 -1.09261655 -0.01723456 -0.11912808  1.00310974 -0.03554892
  0.37172662 -0.80275446 -1.09403333  0.14807976  1.528502    1.37165773
 -1.28495439 -1.86610217 -1.10983074 -2.08966116 -1.7039365  -0.02930304
  0.65071661 -0.47253411 -0.46084567  0.3881

-0.011060690999698721

In [ ]:
print("varianza de mi arreglo")
np.var(arreglo)

# esta mal la varianza como mucha da 1

varianza de mi arreglo


1.1434345968878765

In [ ]:
#calcular la media haciendo el promedio usando np.sum

suma = np.sum(arreglo)
prom = suma / 100

print(prom)


-0.011060690999698721


In [ ]:
 arreglo = np.random.randn(100)

 prom = np.mean(arreglo)

 numerador = np.sum((arreglo - prom )**2)

 varianza = numerador /100

 print("varianza:")
 print(varianza)



varianza:
1.1434345968878765


In [ ]:
arreglo = np.random.randn(10)

print(arreglo)

[-0.43793118  1.24788376 -2.12201656  0.94781622  2.01534592 -0.67459504
  1.66068941  0.54389698 -0.43831365 -1.14121881]
